### ISSUE TITLE
ChannelBot/database/channel_sql.py

### ISSUE THREAD

**Issue by arjun-sangu** [StarkBotsIndustries/ChannelBot#2]
async def get_caption(channel_id):
    q = SESSION.query(Channel).get(channel_id)
    if q and q.caption:
        caption = q.caption
        SESSION.close()
        return caption
    else:
        caption = " "
        SESSION.close()
        return caption

**Comment by StarkBotsIndustries** [comment]
Confirmed this is a bug and resolved
